  /* make icons at extreme ends*/
  @font-face {
    font-family: android;
    src: url(android.ttf)
  }

/* ----------------------------------------------
 * Generated by Animista on 2021-1-24 1:4:15
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes slit-in-horizontal{0%{-webkit-transform:translateZ(-800px) rotateX(90deg);transform:translateZ(-800px) rotateX(90deg);opacity:0}54%{-webkit-transform:translateZ(-160px) rotateX(87deg);transform:translateZ(-160px) rotateX(87deg);opacity:1}100%{-webkit-transform:translateZ(0) rotateX(0);transform:translateZ(0) rotateX(0)}}@keyframes slit-in-horizontal{0%{-webkit-transform:translateZ(-800px) rotateX(90deg);transform:translateZ(-800px) rotateX(90deg);opacity:0}54%{-webkit-transform:translateZ(-160px) rotateX(87deg);transform:translateZ(-160px) rotateX(87deg);opacity:1}100%{-webkit-transform:translateZ(0) rotateX(0);transform:translateZ(0) rotateX(0)}}

  body {
    font-family: Arial, Helvetica, sans-serif;
    font-weight: 400;
    /*color: rgba(255, 255, 255, .5);*/
    font-family: android;

  }

  * {
    padding: 0;
    margin: 0;
    box-sizing: border-box;
  }

  .container {
    color: #fff;
    height: 100vh;
    background: #201028;
    padding: 1rem;
    position: relative;
  }



  #output-controls {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0 .25rem;

  }



  /*style the app title and subtitle */
  #hero {
    text-align: center;
    margin: 0 2.75rem;
    padding: 0 1.75rem;
  }

  #hero h1 {
    font-weight: 300;
    font-family: android;
  

  }

  #hero div {
    color: #fff;
    padding: .5rem 1rem;
  }

  #hero {
    display: flex;
    flex-direction: column;
    justify-content: space-between;

  }

  #whatsapp-layer {
    position: relative !important;
    margin-top: 15vh;
  }

  #whatsapp-layer input {
    width: 100%;
    height: 2.5rem;
    border: none;
    padding: 0 5%;
    border-bottom: #fff solid .1px;
    text-align: center;
    outline: none;
    background: transparent;
    color: #fff;

  }

  #whatsapp-layer div {
    font-size: 70%;
    color: #fff;

  }


  #divider {
    margin-top: 40vh;
    color: #fff;

  }

  #output-controls {
    position: fixed;
    left: 0;
    bottom: 0;
    background: #f5f5f5;
    width: 100%;
    height: 7.5vh;
    padding: 0 .75rem;
    border-radius: 20px 20px 0 0;
  }

  #output-controls img:hover {
    background: rgba(244, 56, 120, .01);
    transform: scale(1.45);
    transition: all .2s cubic-bezier(0.23, 1, 0.320, 1);
  }

  #charLength {
    font-size: 70%;
    font-style: italic;
  }
  
  .slit-in-horizontal{-webkit-animation:slit-in-horizontal .45s ease-out both;animation:slit-in-horizontal .45s ease-out both}
  
  
  
  
    /*<style type="text/css" media="all">*/
    @keyframes spin {
      0% {
        transform: rotate(0deg);
      }

      100% {
        transform: rotate(360deg);
      }
    }

    @-webkit-keyframes swing-in-top-bck {
      0% {
        -webkit-transform: rotateX(70deg);
        transform: rotateX(70deg);
        -webkit-transform-origin: top;
        transform-origin: top;
        opacity: 0
      }

      100% {
        -webkit-transform: rotateX(0deg);
        transform: rotateX(0deg);
        -webkit-transform-origin: top;
        transform-origin: top;
        opacity: 1
      }
    }

    @keyframes swing-in-top-bck {
      0% {
        -webkit-transform: rotateX(70deg);
        transform: rotateX(70deg);
        -webkit-transform-origin: top;
        transform-origin: top;
        opacity: 0
      }

      100% {
        -webkit-transform: rotateX(0deg);
        transform: rotateX(0deg);
        -webkit-transform-origin: top;
        transform-origin: top;
        opacity: 1
      }
    }

    @-webkit-keyframes swing-in-top-bck {
      0% {
        -webkit-transform: rotateX(70deg);
        transform: rotateX(70deg);
        -webkit-transform-origin: top;
        transform-origin: top;
        opacity: 0;


      }

      100% {
        -webkit-transform: rotateX(0deg);
        transform: rotateX(0deg);
        -webkit-transform-origin: top;
        transform-origin: top;


      }
    }

    @keyframes swing-in-top-bck {
      0% {
        display: none;
        -webkit-transform: rotateX(70deg);
        transform: rotateX(70deg);
        -webkit-transform-origin: top;
        transform-origin: top;
        opacity: 0
      }

      100% {
        -webkit-transform: rotateX(0deg);
        transform: rotateX(0deg);
        -webkit-transform-origin: top;
        transform-origin: top;
        opacity: 1;
      }
    }



    @-webkit-keyframes active-layer {
      from {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-transform-origin: center center;
        transform-origin: center center;
        -webkit-animation-timing-function: ease-out;
        animation-timing-function: ease-out
      }

      10% {
        -webkit-transform: scale(.91);
        transform: scale(.91);
        -webkit-animation-timing-function: ease-in;
        animation-timing-function: ease-in
      }

      17% {
        -webkit-transform: scale(.98);
        transform: scale(.98);
        -webkit-animation-timing-function: ease-out;
        animation-timing-function: ease-out
      }

      33% {
        -webkit-transform: scale(.87);
        transform: scale(.87);
        -webkit-animation-timing-function: ease-in;
        animation-timing-function: ease-in
      }

      45% {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-animation-timing-function: ease-out;
        animation-timing-function: ease-out
      }
    }

    @keyframes active-layer {
      from {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-transform-origin: center center;
        transform-origin: center center;
        -webkit-animation-timing-function: ease-out;
        animation-timing-function: ease-out;
      }

      10% {
        -webkit-transform: scale(.91);
        transform: scale(.91);
        -webkit-animation-timing-function: ease-in;
        animation-timing-function: ease-in
      }

      17% {
        -webkit-transform: scale(.98);
        transform: scale(.98);
        -webkit-animation-timing-function: ease-out;
        animation-timing-function: ease-out;

      }

      33% {
        -webkit-transform: scale(.87);
        transform: scale(.87);
        -webkit-animation-timing-function: ease-in;
        animation-timing-function: ease-in
      }

      45% {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-animation-timing-function: ease-out;
        animation-timing-function: ease-out;
      }

    }

    #init {
      width: 10vh;
      height: 10vh;
      border-radius: 50%;
      border: .45rem solid rgba(255, 255, 255, .5);
      border-top: .45rem #fff solid;
      animation: fade-in, 2s linear .5s, spin 2s ease-out infinite .5s;
      position: absolute;
      top: calc(40vh);
      left: calc(40vw);
      background: transparent;
    }



    #menu {
      display: none;
      flex-direction: column;
      position: absolute;
      top: 23;
      z-index: 1000;
    }

    #menu img {
      width: 35px;
      fill: #fff;
      padding: .25rem;
      border-radius: 5px;
      cursor: pointer;
    }

    #menu img:hover {
      transform: scale(1.25);
      transition: all .2s cubic-bezier(0.23, 1, 0.320, 1);
      border-radius: 7px;
    }

    .dis {
      display: block;
    }



    .swing-in-top-bck {
      animation: swing-in-top-bck .5s cubic-bezier(.175, .885, .32, 1.275) both;
      animation-delay: 2s;

    }

    .active-layer {
      -webkit-animation: active-layer 3.5s ease-in-out 1 both;
      animation: active-layer 3.5s ease-in-out infinite both;
    }


    .scale-in-center {
      -webkit-animation: sec .5s cubic-bezier(.25, .46, .45, .94) both;
      animation: ssc .5s cubic-bezier(.25, .46, .45, .94) both;
      animation-delay: 2s;
    }

    .layer {
      display: none;
    }
